### ISSUE TITLE
Strange view of properties in winery

### ISSUE THREAD

**Issue by jonasheinisch** [CloudCycle2/YAML_Transformer#137]
Fix it!

**Comment by msteffl** [comment]
we have to setup Open Tosca Container first to check the correct functionality of our csar. Maybe strange view doesn't matter

**Comment by msteffl** [comment]
If our csar is wrong...here the differences between our and working csar in Winery
![ourmoodledb](https://cloud.githubusercontent.com/assets/5903258/6919288/266a4e8e-d7b6-11e4-8c41-147860b215c4.PNG)
![workingmoodledb](https://cloud.githubusercontent.com/assets/5903258/6919289/266babbc-d7b6-11e4-9591-e3957f25f36d.PNG)

**Comment by seeebiii** [comment]
Are there any updates on this issue?

**Comment by koppor** [comment]
Any comment why it can be closed? ^^

**Comment by msteffl** [comment]
all the properties that are shown correctly are in winery namespace because they were created in winery. When we import our own NodeTypes with new properties they are not in the winery namespace and so they were not shown correctly.

When we look for the properties after deploying in the OpenTosca Container they exist in the NodeInstances and all seems to be ok. We checked it with Tim.
