### ISSUE TITLE
RequirementTypes QNames

### ISSUE THREAD

**Issue by jonasheinisch** [CloudCycle2/YAML_Transformer#157]
The TypeMapper do not implement a switching for RequirementTypes. This needs to be fixed!

**Comment by msteffl** [comment]
in our Moodle csar the error only happens by SoftwareContainerRequirement

I changed namespace in the XML manually to ns1 and after that, the completly empty winery accepts it. 

So may its only an individual error when using SoftwareContainerRequirement.

**Comment by msteffl** [comment]
i checked the possibility to map the baseTypes RequirementTypes but there is no standard naming convention like tosca.requirements.ServerContainer. So i think mapping to the baseTypes is not the best choice.

When we have to create a requirement, requirementType should be created automatically. Think this is already implemented. The problem here is, that requirementTypes can be created multiple times. E.g. when 2 NodeTemplates using same requirement, requirementType will be created 2 times. I think when removing the double occuring types to make the file work SoftwareContainerRequirement was completely removed and thats the reason why it did not work.

So i think we have to fix the stuff with the mutiple occuring RequirementTypes and then it will work.
