### ISSUE TITLE
Source of VisualParadigmXMLSplitterRejoiner.jar

### ISSUE THREAD

**Issue by koppor** [CloudCycle2/YAML_Transformer#166]
The source directory doesn't seem to contain the source for "VisualParadigmXMLSplitterRejoiner.jar". Where is that source located?

**Comment by seeebiii** [comment]
The jar is contained in: https://github.com/CloudCycle2/YAML_Transformer/tree/master/YamlUMLModel

Nevertheless, we haven't used the jar since the end of last year. It was a first concept to design our YAML model in Visual Paradigm, but it didn't work well, so we continued writing the models directly within Java classes.

**Comment by koppor** [comment]
I asked about the *source* of that jar, not the jar itself. :)

**Comment by seeebiii** [comment]
If you want to know who the owner and creator of that file is: it's @iaavo

**Comment by seeebiii** [comment]
Can we close this issue? @koppor @iaavo
